### ISSUE TITLE
missing JSON files in dataset directory

### ISSUE THREAD

**Issue by srulikbd** [ROGERDJQ/RoBERTaABSA#2]
thanks a lot for this great paper and repository!

the code try to load jsons from the datasets, but there are only train and test XML files.
I used an online tool to convert it to JSON, and it seem to fine tune ok on them.

**Comment by srulikbd** [comment]
but strangely it spit an error while fien tuning using RoBERTa en model. but it succeed using BERT model:

`ubuntu@ip-172-31-16-130:~/RoBERTaABSA/Train$ python3 finetune.py --data_dir '/home/ubuntu/RoBERTaABSA/Dataset/' --dataset Laptop --model_name roberta-en-large
2021-05-26 13:59:44.057245: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-26 13:59:44.057287: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Namespace(batch_size=32, data_dir='/home/ubuntu/RoBERTaABSA/Dataset/', dataset='Laptop', lr=2e-05, model_name='roberta-en-large', save_embed=1)
Traceback (most recent call last):
  File "finetune.py", line 115, in <module>
    data_bundle = get_data()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastNLP/core/utils.py", line 360, in wrapper
    results = func(*args, **kwargs)
  File "finetune.py", line 109, in get_data
    data_bundle = ResPipe(model_name=args.model_name, mask=mask).process_from_file(
  File "/home/ubuntu/RoBERTaABSA/Train/pipe.py", line 114, in process_from_file
    data_bundle = ResLoader().load(paths)
  File "/home/ubuntu/RoBERTaABSA/Train/pipe.py", line 144, in load
    data = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
`

**Comment by ROGERDJQ** [comment]
I suggest changing the name of the .json file in the Dataset folder to the form in  code https://github.com/ROGERDJQ/RoBERTaABSA/blob/c40b52c2bc15c44cc1d16046053ed0b3c64619a4/Train/pipe.py#L133-L140, or change the file name in this code to Test/Train_biaffine_depparsed.json.

Yet I am also wondering why BERT could run successfully.
